version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hrms
    ports:
      - "3306:3306"

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - app
